### PR TITLE
Draft PR in order to use different number of profiles between contrast / repetition

### PR DESCRIPTION
**Pull request by aTrotier**
linked to issue : #138 

- First correction : correct encodingSize  for acq to raw + ut

### CODE REVIEW

**Comment by aTrotier** [comment]
@tknopp it was easier than I thought :)

Right now I only need one temporal dimension with dedicated trajectories. But If at some points if I want to implement [XD-GRASP reconstruction ](https://onlinelibrary.wiley.com/doi/10.1002/mrm.25665) for cardiac / respiratory, I will also need a second dimension.

Is that ok if I also implement the possibility to have various trajectory along either contrasts and repetitions ?
Or do you prefer to let the repetition dimension as it is and later adding another dimension ? (like segment / phase / set if we want to stick to the MRD flags)

**Comment by tknopp** [comment]
> Is that ok if I also implement the possibility to have various trajectory along either contrasts and repetitions ?

Yes sounds good. You can ping me once this is ready to merge.

**Comment by aTrotier** [comment]
As suggested by @JeffFessler, I have created an example with literate to show how to use that possibility.
It works locally for me and gives this html pages :
[index.html.zip](https://github.com/MagneticResonanceImaging/MRIReco.jl/files/10393025/index.html.zip)

Maybe @mrikasper also want to take a look for documentation enhancements

**Comment by aTrotier** [comment]
@tknopp maybe we can merge this PR.


I'll create another PR for the repetition later. 
It will require a lot of changes and maybe breaking ones.

**Comment by aTrotier** [comment]
The example is generated with Literate.jl but I don't see the plot. I also had that issue in local because I had to dev the packages.
I think the package used in docs/ are not the one on main.

@JeffFessler Do you know how to show the error in the page build by literate ?

**Comment by JeffFessler** [comment]
I don't have any experience with using Literate when there are subpackages.  Seems tricky!
For a single-package repo, I first debug the Literate examples locally by running `julia -- make.jl` in the `docs` directory like here: https://github.com/JeffFessler/MIRT.jl/tree/main/docs
When I think it works, I submit a PR and the CI runs the docs in the cloud and I can look at the action outputs to see if it runs.  Especially the "BuildAndDeploy" tab for the Documentation build, such as this:
https://github.com/JeffFessler/MIRT.jl/actions/runs/3644407653/jobs/6153624826
You can also use "push preview" to see if it builds properly but I don't use that too often:
https://documenter.juliadocs.org/stable/man/hosting/#gh-pages-Branch

**Pull request merged**
