### PR TITLE
update Mridataexample

### PR DESCRIPTION
**Pull request by aTrotier**

### CODE REVIEW

**Comment by aTrotier** [comment]
2 remarks :
- I used a secondary tmpVec2 vector to store the results of fftshift! 
- Wavelets.jl does not handle our matrix size. One of my PR has been merge 4 months ago but not release has been done -> `Pkg.add(Pkg.PackageSpec(name="Wavelets",rev="master"))`

**Comment by tknopp** [comment]
cool thanks, I will have a look later or tomorrow.

**Comment by aTrotier** [comment]
```julia
@time img = fftshift( reconstruction(acqData2d, params).data[:,:,:,1,1], 2)
```

Why do we have to use the fftshift ? It is just because the offset along that dimension is not corrected  ? If yes maybe we can use that as a test to implement the offset correction from ismrmrd files

**Comment by tknopp** [comment]
> Why do we have to use the fftshift ?

I don't know, I just translated 1to1 the `FFTOp` how it was used before. I don't want `MRIBase` to depend on `MRIOperators`. Therefore this small workaround. We already have the indirect dependency on `FFTW` because of `NFFTTools`.

**Comment by aTrotier** [comment]
I was talking about the fftshift after reconstruction not the one to replace the fftop.

I'll keep that in mind for later

**Comment by tknopp** [comment]
> Why do we have to use the fftshift ? It is just because the offset along that dimension is not corrected ? If yes maybe we can use that as a test to implement the offset correction from ismrmrd files

Ah sorry, I misinterpreted  that. Yes, I guess that the `fftshift` is just because of the `offset` not being taken into account. So this seems to be a workaround we should fix. Will still still merge now, since we can do this in follow up work. And yes, this file would be a nice unit test.

**Pull request merged**
