### PR TITLE
add ecalib for 3D acq and test

### PR DESCRIPTION
**Pull request by aTrotier**
Maybe we should wait until the other PR is resolved #115 ? 
Is it possible to directly dispatch when acq is 2D or 3D ?

### CODE REVIEW

**Comment by tknopp** [comment]
yes, we should extend it to ND but let's do it after https://github.com/MagneticResonanceImaging/MRIReco.jl/pull/115.

**Comment by tknopp** [comment]
I took the tests from this PR and extended the `espirit` high level function to handle 3D data as well. Thank you for preparation, this was very helpful! The code is here: https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/dee443c9db8d7b262bfeb4af9b1763a91160f7c2

In the long run, I want AcquisitionData to be parametric in `D`. Now I needed to dispatch on the calibsize dimension which only works if it is explicitly passed.

**Comment by aTrotier** [comment]
Great! In the long term do you think we should also be able to dispatch between Cartesian and non Cartesian ? 
We have a lot of if case or @error from this difference.

**Comment by tknopp** [comment]
yes probably. We once had something in that direction (a dedicated type hierarchy for trajectories) but that was not really working well. I will have a look at that when looking at making `AcquisitionData` parametric.

**Pull request closed without merging**
