### PR TITLE
issue with NFFTTools 0.2.4 -> force compat to 0.2.3

### PR DESCRIPTION
**Pull request by aTrotier**

### CODE REVIEW

**Comment by aTrotier** [comment]
It was just a test to see if the error was related to my minor modification.

@tknopp it seems it is an issue with the latest version of NFFT.jl no ? I see that you change the version to 0.14 -> 0.13 which might explain why MRIReco is not working with that commit.

**Comment by tknopp** [comment]
I can't look at this right now. The issue was that I skipped one version and therefore needed to get back. But I can do yet another NFFT release soon if that fixes the issue.

**Comment by aTrotier** [comment]
No rush. I was just worried yesterday to see the CI failed with my minor
modification !

Le jeu. 28 juil. 2022 à 13:22, Tobias Knopp ***@***.***> a
écrit :

**Comment by aTrotier** [comment]
If I put :
```
[[deps.NFFT]]
deps = ["AbstractNFFTs", "Distributed", "FFTW", "FLoops", "Graphics", "LinearAlgebra", "Printf", "Random", "Reexport", "SparseArrays", "SpecialFunctions"]
git-tree-sha1 = "78f019d7c07fd89ca9e783f365a72431b1c4efee"
uuid = "efe261a4-0d2b-5849-be55-fc731d526b0d"
version = "0.13"

[[deps.NFFTTools]]
deps = ["AbstractFFTs", "AbstractNFFTs", "FFTW", "LinearAlgebra"]
git-tree-sha1 = "8edaa06e0424e85b9f2eda32f7c5f4624101e40c"
uuid = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
version = "0.2.4"
```

The first part of the tests pass but failed with :
```julia
Test Summary:   | Pass  Error  Total
Linear Operator |    5      1      6
ERROR: LoadError: Some tests did not pass: 5 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/aurelien/.julia/dev/MRIReco/test/testOperators.jl:151
```

**Error:**
```julia
Linear Operator: Error During Test at /Users/aurelien/.julia/dev/MRIReco/test/testOperators.jl:144
  Got exception outside of a @test
  type NFFTPlan has no field x
  Stacktrace:
    [1] getproperty(x::NFFT.NFFTPlan{Float64, 2, 1}, f::Symbol)
      @ Base ./Base.jl:42
    [2] MRIReco.NFFTToeplitzNormalOp(S::NFFTOp{ComplexF64}, W::UniformScaling{Bool})
      @ MRIReco ~/.julia/dev/MRIReco/src/Operators/NFFTOp.jl:99
```

Do you get the same error ?

**Comment by tknopp** [comment]
Yes, NFFT.jl changed internally. Just replace `x` by `k`

**Comment by aTrotier** [comment]
My bad, I read diagonally and thought it was related to NFFT.jl :)

I made a new commit that use the last version of NFFT and NFFTools + replace x by k.

**Pull request merged**
