### PR TITLE
add other coil compressions

### PR DESCRIPTION
**Pull request by aTrotier**
I am preparing the field to add other coil compressions.
Are you ok with the modification before going further ?

### CODE REVIEW

**Comment by tknopp** [comment]
> Are you ok with the modification before going further ?

yes, looks fine!

**Comment by aTrotier** [comment]
I have added the coil compression directly on kspace : kx,ky,kz,coils,echos,repetitions
I think it will be good to put the slice dimension maybe along dimension 7.

Right now, kDataCart extracts the slice along the dim 3 but when I want to convert back the kspace in an acquisition object I assume it is a 3D kspace. 
same for coilcompression, I assume the kspace is in 3D and not a multislice acquisition.

**Comment by aTrotier** [comment]
Results on the datasets available here (32 channels) : 
https://people.eecs.berkeley.edu/~mlustig/software/ESPIRiT_demo/demo_GCC.html

image

image

- RMSE SCC (32 -> 6) : 8.0e-5
- RMSE GCC (32 -> 6) : 3.5e-5

**Comment by tknopp** [comment]
I can't review this in detail right now but the test look all good and since this is definitely a clear improvement I merge this now. Improvements can be made later on.

**Pull request merged**
