### PR TITLE
incl. LinearOperatorCollection v2

### PR DESCRIPTION
**Pull request by JakobAsslaender**
@tknopp: can you merge and release this change? I still don't understand, how to release these sub-packages without breaking everything. 

Another quick question: the compat helper doesn't work with sub-projects, does it? It would be nice to get that working to avoid the manual labor of updating packages.

### CODE REVIEW

**Comment by JakobAsslaender** [comment]
It seems that the CI failures are unrelated to this compat update, they are the same failures as the master branch. I tested the subpackage locally and it passed all tests.

**Comment by tknopp** [comment]
@nHackel: could you comment on this? I recall that we are currently in a bad state and it requires merging the gpu branch?

**Comment by nHackel** [comment]
The GPU branch is ready to be merged and increases the compat for LinearOperatorCollection to 2.0

**Comment by nHackel** [comment]
I think the bad state was partially that in the current master we are not yet using the correct keyword for the normal operator. I don't recall all the details, but things should be fixed in the gpu branch

**Comment by tknopp** [comment]
ok, merged. I would then directly release 0.9, right?

**Comment by nHackel** [comment]
Hmm it's probably for the best. MRIOperators definitely had breaking changes and increased to 0.3. 

From an interface perspective I think MRIReco only had bug fixes and the new arrayType keyword, but we increased the requirements for MRIOperators to the new version...which I think would count as a breaking change since we increased our lower compat bound

**Pull request closed without merging**
