### PR TITLE
Draft for discussion : Subspace implementation

### PR DESCRIPTION
**Pull request by aTrotier**
Hi,

I am working on a subspace reconstruction for T2 mapping Multi-Echo Spin-Echo sequence. I am currently doing the reconstruction part with BART.

This is a draft to implement the reconstruction in Julia. It seems to work (at least on fully datasets) : 
- for multi-coil multi-echo -> same fix than in #146 
- for now the reconstruction is in a specific reconstruction pipeline `params[:reco] = "multiCoilMultiEchoSubspace"`. Maybe we can directly put it in the multi-echoes operators ?

Let me know what you think I should change ?

I think @JakobAsslaender and @alexjaffray are also interested in / using a similar implementation

example : 
```julia
b = BrukerFile("MESE_FULLY")
raw = RawAcquisitionData_MESE(b)
acq = AcquisitionData(raw,OffsetBruker=true)

sens = espirit(acq)


## generate basis

function createExpBasis(TE_vec::AbstractVector{T},T2_vec::AbstractVector{T}) where {T<:Real}
    nTE = length(TE_vec)
    nSimu = length(T2_vec)
    expSignal = zeros(T,nSimu,nTE)

    for (i,T2) in enumerate(T2_vec)
        expSignal[i,:] = exp.(-TE_vec/T2_vec[i])
    end

    return expSignal
end

T = Float32
TE_vec = 7:7:50*7
T2_vec = 1:1:2000

sDict = createExpBasis(T.(TE_vec),T.(T2_vec))
lines(TE_vec,sDict[200,:])

svd_obj = svd(sDict)
V = svd_obj.V

############### TRY RECO ###############
########################################


params = Dict{Symbol, Any}()
#params[:reco] = "direct"
params[:reconSize] = acq.encodingSize

params[:reco] = "multiCoilMultiEchoSubspace"
params[:regularization] = "L2"
params[:λ] = 1.e-3
params[:iterations] = 1
params[:solver] = "cgnr"
params[:senseMaps] = sens
params[:basis] = Complex.(V[:,1:5])

im_reco_sub = reconstruction(acq,params)

heatmap(abs.(im_reco_sub.data[:,:,16,5,1,1]),colormap = :greys)


## Apply subspace

I2 = applySubspace(im_reco_sub.data,Complex.(V[:,1:5]))
heatmap(abs.(I2[:,:,16,15,1,1]),colormap = :greys)

im2 = applySubspace(im_reco_sub, Complex.(V[:,1:5]))

heatmap(abs.(im2[:,:,16,15,1,1]),colormap = :greys)

```

### CODE REVIEW

**Comment by JakobAsslaender** [comment]
Hi,
I already implemented this for non-Cartesian trajectories in [MRFingerprintingRecon.jl](https://github.com/JakobAsslaender/MRFingerprintingRecon.jl) (not the best name, I know). @andrewwmao is currently working on a Cartesian implementation.

**Comment by JakobAsslaender** [comment]
Probably :). I guess the best way might be to change ownership to MagneticResonanceImaging? I think I was just hesitant to do so because the package is still WIP. In terms of MRIReco.jl itself, I have no objections against wrappers, but I would be hesitant to move the into MRIReco as I personally prefer a more low-level interface.

**Comment by JakobAsslaender** [comment]
Ha, fair point! OK, I will move it.

**Comment by aTrotier** [comment]
I have some kind of implementation + test ready. 
I have to try it on real accelerated k-space to see the results, I guess with fista the results won't be as good as with BART (issue #114 ).

@JakobAsslaender I suppose your implementation is faster than mine. Do you think we should keep the high level implementation ?

**Comment by aTrotier** [comment]
shape mismatch with wavelet regularization :)

**Comment by aTrotier** [comment]
@JakobAsslaender I am not able to get a working "multiCoil" reconstruction  with the diagonal operator build like that :

```julia
E = DiagOp(repeat(ftOp, inner=numChan)...) ∘ S # do not work
```

but it works (and is stable) with this line (which correspond to the high level implementation of "multiCoil"-

```julia
E = DiagOp(ftOp[1], numChan) ∘ S
```

It is an issue with "repeat" it works if I replace it by 
```julia
  ops2 = [copy(ftOp[1]) for n=1:numChan]
  E= DiagOp(ops2...)
```

I have to check how to change that in the high level interface

**Comment by alexjaffray** [comment]
Thanks @aTrotier for pushing this forward. As far as the question about repeat() vs. copy(), my intuition is that operators which maintain any computed or mutating internal variables  must be copied. 

I will pull this and try it out with some of my data

**Comment by aTrotier** [comment]
Thank @alexjaffray, I don't see any reason to broke my branch :)
I'll try to finish the literate example in the doc today and then change the PR to review

**Comment by aTrotier** [comment]
Seems good on my side. 

We will have to benchmark the speed / memory / precision against BART

**Comment by aTrotier** [comment]
Can I merge It ?

**Pull request merged**
