### PR TITLE
Read Bruker method file only the first time

### PR DESCRIPTION
**Pull request by aTrotier**
PR corresponding to issue #94 

- method file is only read one time. 
- A test has been added : read a parameters should take less than < 0.0001 s

---
# Results on my mac
┌ Info: Read parameters timing
│   t1 = 0.380862047
└   t2 = 1.51e-6

### CODE REVIEW

**Comment by tknopp** [comment]
Ah, was the issue that the parameter file was parsed several times?

**Comment by aTrotier** [comment]
> Ah, was the issue that the parameter file was parsed several times?

yes, b.methodRead was set to`true` but not taken into account by the else + condition line.
It is weird else + condition does not throw an error.

**Comment by tknopp** [comment]
Ok, thanks! Will merge. CI problems are because of NFFT.

**Comment by aTrotier** [comment]
Yes I know. 
If you merge #95. I think it will work again no ?

**Comment by tknopp** [comment]
There is still a version conflict but that might be because of CI not using the master of all sub packages. So we might need some version on the subpackage.

**Pull request merged**
