### PR TITLE
Reco Bruker 3DUTE initial implementation

### PR DESCRIPTION
**Pull request by aTrotier**
**This PR is not suppose to be merged for now** 

# Goal
It is an initial implementation of a 3DUTE reconstruction from the standard 3D UTE Bruker acquisition.

# Test
You can find a testing script here with the associated datasets (a 3DUTE with a matrix of 96x96x96 and 2 NR)
https://drive.google.com/drive/folders/1roh0tRhAQTsqe27iKaHHhuGGi9n4MA65?usp=sharing

## Results of test.jl :

RMSE = 0.30 
test

# Remarks
- I had to change the oversampling for the nufft in order to estimates the weights in order to reach a good image quality.
- For now I have split the conversion from Bruker to Raw in a specific file with a lot of copy/paste from the `function RawAcquisitionDataFid(b::BrukerFile)`. We should discuss how to manage the factorization.
- I had to bypass the `encStep` problem by creating custom functions only called if : 
`if (f.params["trajectory"] == "custom")`
Again a lot of repetition with the standard functions but I am not using the EncStep1/EncStep2 (which are all equal to 0 during the conversion from bruker to acq).
- I have to try if standard reco works

# Discussions
1-  Reconstruction only return 1 repetition (the for loop is not available for NR)
2- Only one trajectory is stored during conversion from raw to acq, should we keep one for each NR,contrast,slices ?

Let me know what are your thoughts about that first try.

### CODE REVIEW

**Comment by aTrotier** [comment]
Adding a circshift along the slice direction i get a rmse under 10 percent :

```julia
b = BrukerFile("data/UTE3D_NR2/")

raw = RawAcquisitionData_3DUTE(b)
acq = AcquisitionData(raw);  # TODO vérification des modifications qui ont étaient effectuée


params = Dict{Symbol, Any}()
params[:reco] = "direct"
if (acq.encodingSize[3]>1)
    params[:reconSize] = (acq.encodingSize[1],acq.encodingSize[2],acq.encodingSize[3]);
else
    params[:reconSize] = (acq.encodingSize[1],acq.encodingSize[2]);
end


Ireco = reconstruction(acq, params);
#@test size(Ireco) == (raw.params["encodedSize"][1], raw.params["encodedSize"][2], raw.params["encodedSize"][3], 1, raw.params["receiverChannels"])

Isos = sqrt.(sum(abs.(Ireco).^2,dims=5));
Isos = Isos ./ maximum(Isos);

I2dseq = recoData(b)
I2dseq = I2dseq ./ maximum(I2dseq);

# reorient
I2dseq = permutedims(I2dseq,(2,1,3,4))
I2dseq = circshift(I2dseq,(0,0,1,0))
#@test norm(vec(I2dseq)-vec(Isos))/norm(vec(I2dseq)) < listNormValues[i]

sl = 60
p1 =     Plots.heatmap(abs.(Isos[:,:,sl,1,1]),title = "MRIReco",color = :greys,aspect_ratio = 1, axis=nothing, lims=(1,95))
p2 =     Plots.heatmap(abs.(I2dseq[:,:,sl,1]),title = "Bruker",color = :greys,aspect_ratio = 1 , axis=nothing, lims=(1,95))

diff = abs.(abs.(I2dseq[:,:,sl,1]) - abs.(Isos[:,:,sl,1,1] )) ./ abs.(I2dseq[:,:,20,1])
p3 =     Plots.heatmap(diff,title = "Diff",color = :greys,aspect_ratio = 1 , axis=nothing, lims=(1,95))
Plots.plot(p1,p2,p3,layouts=(1,3))

MRIReco.norm(vec(I2dseq)-vec(Isos))/MRIReco.norm(vec(I2dseq))
```

**Comment by tknopp** [comment]
Great that we have support for more sequences. What I don't get is, why we need `trajectoryCustom`, `rawdataCustom` and `RawAcquisitionData_3DUTE`. Its fine that we have custom code but the dispatch should be done within the functions `RawAcquisitionData`, `trajectory` and `rawdata`.

**Comment by tknopp** [comment]
> Can you upload the dataset in order to create a test ?

Yes, will do later this week.

**Comment by aTrotier** [comment]
Thanks,

Minor question @tknopp :
I am not able to make the test working in runtest.jl (it works with the testing script).
It seems that the testing environnement use the unchanged MRIFiles/MRIBase module. How can I tell Julia to use the version in .dev ?

**Comment by tknopp** [comment]
The data is now included, see https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/eb6e54f67732c1247b3f1be6d64db0a602bdcd8b
It is in the folder `BrukerFile/3D_UTE_NR2/`
To test this locally, you need to dev MRIFiles/MRIBase as well.

**Comment by aTrotier** [comment]
Thanks,
with `dev MRIFiles/MRIBase` my test is working. 
Should I change the version of MRIFiles/MRIBase in order to make the CI tests works ?

**Comment by tknopp** [comment]
No, I will do this. Are you already using the artifact?

**Comment by aTrotier** [comment]
yes.
I need to dev MRIFiles and MRIBase. The CI is not using the version in that PR. 
Am I missing something to make it work without making a PR of first MRIBase/MRIFiles ?

**Comment by tknopp** [comment]
> Am I missing something to make it work without making a PR of first MRIBase/MRIFiles ?

no. There is no chance that you can make CI happy in this setting. I will try out locally and then do the releases.

**Comment by tknopp** [comment]
I made the releases but CI is only partially happy. It seems that there is probably just not enough memory for the UTE dataset on the windows CI: https://github.com/MagneticResonanceImaging/MRIReco.jl/runs/6240907107?check_suite_focus=true

**Comment by aTrotier** [comment]
Ok I will acquire a smaller dataset after ismrm

Le sam. 30 avr. 2022 à 18:06, Tobias Knopp ***@***.***> a
écrit :

**Pull request merged**
