### PR TITLE
Implement reconstruction for Bruker PV360

### PR DESCRIPTION
**Pull request by aTrotier**
related to #157

### CODE REVIEW

**Comment by aTrotier** [comment]
CS reconstruction with MRIReco vs Bruker :
```julia
b = BrukerFile("2023_SUPP_CryoTest/CS")

raw = RawAcquisitionData(b)
acq = AcquisitionData(raw,OffsetBruker=true)


sens = espirit(acq,eigThresh_2 = 0);

params = Dict{Symbol, Any}()
params[:reco] = "multiCoil"    # encoding model
params[:reconSize] = acq.encodingSize
params[:sparseTrafo] = "Wavelet" #sparse trafo
params[:regularization] = "L1"       # regularization
params[:λ] = 20.0
params[:solver] = "admm"    # solver
params[:iterations] = 3
params[:iterationsInner] = 2
params[:ρ] = 1.0e-1
params[:senseMaps] = sens

img_CS = abs.(reconstruction(acq, params))
```

image

The code handle the following cases for FLASH sequence :
- 2D
- 3D
- Phase oversampling (when phase oversampling is used the reconstructed matrix is not cropped with MRIReco)
- Grappa
- CS

I have to check if the loops works (NA/NR/NAE).

Some informations are lost about the acquisition like because the visu_pars file is now in the pdata folder (and sometime I disable the reconstruction
-   params["measurementID"] = visuExperimentNumber(b)
-   params["patientName"] = b["VisuSubjectName"] 

The visu files is now in the pdata/i folder

**Comment by aTrotier** [comment]
For information, the code also work with the MGE sequence (at least in fully)
But not if you use some specific acceleration methods like :
- Interpolation (zero-filliin)
- Partial Fourier

I need to figure out how to compute the reconstruction matrix size (it is not directly stored in the metadata...)

**Comment by aTrotier** [comment]
Ok, seems good on my side for most of the cases.
I have to relaunch the CI when the dataset is available if it works then we can merge this PR.

**Comment by tknopp** [comment]
I have uploaded the data and replaced the Artifacts.toml directly on your branch. Let's see if CI gets green now.

Very nice that you include some CS data. Is it the data with which you reconstructed above shown images?

**Comment by aTrotier** [comment]
Perfect, now we can merge it ! 
Yes it is the same dataset, if needed, we can use it in the documentation.

Can you make a release of all the package / subpackages I already need that in a lot of project (as well as the subspace implementation for a paper I'm writing)

**Comment by tknopp** [comment]
yea, I can do the releases but may need some days.

**Comment by tknopp** [comment]
@aTrotier: Releases are done. I additionally ported MRIReco from SparsityOperators to LinearOperatorCollection. The later is the successor of the former (more precise name and improved code).

For some reason I needed to adapt the following test accuracy: https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/master/MRIFiles/test/testBrukerFile.jl#L142

I am not sure why but it may be something to do with BrukerFiles being loaded as Float32 instead of Float64 since I also needed to convert the nodes to Float64 since the sampling density calculation just returned zero weights otherwise (see this change https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/c259559ecc715cb6415fce786833dfbce59506f4/MRIBase/src/Datatypes/AcqData.jl#L288)

But I am now happy that all tests pass again. Releasing all the packages when so much happened is quite a journey.

**Pull request merged**
