### PR TITLE
Multiple improvements for BrukerFile

### PR DESCRIPTION
**Pull request by aTrotier**
- Now read all parameters in method which is required because Excitation/Refocuse Pulse names are not starting by "PVM_".
- Minor changes to read the whole pulse structure, not only the first line. I can still find some issues with very specific parameters with multiples parenthesis like :
```C
#$PVM_SliceGeo=( 1 )
(((-1 0 0 0 1 0 0 0 -1, 0 0 0), 30 30 1, <+R;read> <+P;phase> <+S;slice>, 0), 
1, 1, 256, 1, 0, No)

```
- Read all visu params, not only the specific subset.
- recoData read all the "frames" and works for any output types.

Related to #87 and #86

---
NOTES :
1) Bruker store the data like that :
`x,y,z,channel,frame`
where frame is anything -> echo/slice (for complex data the 1st half of data are real and second one imaginary)
For now, the output of recoData is not reordered but because we can also have some post-process data in procno, I think it is more robust like that.
2) I have data with multiple reconstruction of 2D_FLASH :
- 32Float + Magnitude
- 32 Float + Real
- 32 Int + Complex Shuffle
- UInt8 + Magn

@tknopp If you want I can create a test and send you the data

### CODE REVIEW

**Comment by tknopp** [comment]
great! Yes please send me the data and I add it to the test datasets.

**Comment by tknopp** [comment]
Added the new dataset to master: https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/master/test/Artifacts.toml
Locally master tests pass for me.

**Comment by aTrotier** [comment]
Seems good on my side :)

**Comment by tknopp** [comment]
tests pass locally for me.

**Pull request merged**
